// Code generated by options-gen. DO NOT EDIT.
package favorites

import (
	fmt461e464ebed9 "fmt"
	"time"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	inMemory bool,
	configPath string,
	syncConfigPeriod time.Duration,
	maxDisplayLen int,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.inMemory = inMemory
	o.configPath = configPath
	o.syncConfigPeriod = syncConfigPeriod
	o.maxDisplayLen = maxDisplayLen

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("configPath", _validate_Options_configPath(o)))
	errs.Add(errors461e464ebed9.NewValidationError("syncConfigPeriod", _validate_Options_syncConfigPeriod(o)))
	errs.Add(errors461e464ebed9.NewValidationError("maxDisplayLen", _validate_Options_maxDisplayLen(o)))
	return errs.AsError()
}

func _validate_Options_configPath(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.configPath, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `configPath` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_syncConfigPeriod(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.syncConfigPeriod, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `syncConfigPeriod` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_maxDisplayLen(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.maxDisplayLen, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `maxDisplayLen` did not pass the test: %w", err)
	}
	return nil
}
